language: python

python:
  - "3.6.5"
  
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - psql -c 'create database sendit;' -U postgres

script:
  - python manage.py test
  - python manage.py cov

  sudo: required
  
after_success:
  - coveralls