language: python

python:
  - "3.6.5"
  
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - pip install -U pip
  - pip install -U tox coverage coveralls
  - pip install -r requirements.txt

script:
  - nosetests --with-cov --cov tests
  
after_success:
  - codecov
  - coveralls