language: python

python:
  - "3.6.5"

#virtualenv:
#  system_site_packages: true
  
before_install:
  - pip install -r requirements.txt
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

script:
  - pytest --cov=./
  
after_success:
  - codecov
  - coveralls