language: python

python:
  - "3.6.5"
  
before_install:
  - pip install -U pip
  - pip install -U tox coverage coveralls
  - pip install -r requirements.txt
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

script:
  - pytest #--cov=./
  
after_success:
  - codecov
  - coveralls