language: python

python:
  - "3.6.5"
  
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - pip install -r requirements.txt
  - psql -c 'create database travis;' -U postgres

script:
  - nosetests --with-cov --cov app tests/
  
after_success:
  - coveralls