language: python

python:
  - "3.7"  # 3.7 development branch

virtualenv:
  system_site_packages: true
  
before_install:
  - pip install -r requirements.txt
  #- "python run.py install

script:
  - pytest
  
after_success:
  - codecov
  - coveralls